name: Release `wasi-stub`

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number without the leading `v` (e.g. `0.2.0`), should be synced with `Cargo.toml`"
        required: true
      body:
        description: "Description of the release"
        required: true
      dry-run:
        description: "Whether to perform a dry run without creating a real release"
        type: boolean
        required: true
        default: false

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-musl, suffix: "" }
          - { os: windows-latest, target: x86_64-pc-windows-msvc, suffix: .exe }
          - { os: macos-latest, target: x86_64-apple-darwin, suffix: "" }
    name: build ${{ matrix.job.os }}
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --package wasi-stub
      - run: cargo publish --dry-run --package wasi-stub
      - uses: actions/upload-artifact@v4
        with:
          name: wasi-stub-${{ matrix.job.target }}
          path: target/release/wasi-stub${{ matrix.job.suffix }}

  gh-release:
    name: Create GitHub Release
    if: ${{ !inputs.dry-run }}
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Download linux
        uses: actions/download-artifact@v8
        with:
          name: wasi-stub-x86_64-unknown-linux-musl
          path: wasi-stub-x86_64-unknown-linux-musl
      - name: Download windows
        uses: actions/download-artifact@v8
        with:
          name: wasi-stub-x86_64-pc-windows-msvc
          path: wasi-stub-x86_64-pc-windows-msvc
      - name: Download macos
        uses: actions/download-artifact@v8
        with:
          name: wasi-stub-x86_64-apple-darwin
          path: wasi-stub-x86_64-apple-darwin
      - name: Make archives
        run: |
          tar -czvf wasi-stub-x86_64-unknown-linux-musl.tar.gz wasi-stub-x86_64-unknown-linux-musl/wasi-stub
          zip wasi-stub-x86_64-pc-windows-msvc.zip wasi-stub-x86_64-pc-windows-msvc/wasi-stub.exe
          tar -czvf wasi-stub-x86_64-apple-darwin.tar.gz wasi-stub-x86_64-apple-darwin/wasi-stub
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: wasi-stub ${{ github.event.inputs.version }}
          tag_name: wasi-stub-${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.body }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            wasi-stub-x86_64-unknown-linux-musl.tar.gz
            wasi-stub-x86_64-pc-windows-msvc.zip
            wasi-stub-x86_64-apple-darwin.tar.gz

  crates-io:
    name: Publish to crates.io
    if: ${{ !inputs.dry-run }}
    runs-on: ubuntu-latest
    needs: [build] # Only publish if the build succeeds
    environment: crates-io # For enhanced security
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish --package wasi-stub
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
